apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  aws-access-key-id: QUtJQVRTQlpKUUVXUTVXSFNVNlo=
  aws-secret-access-key: Ry9BUFRjd1FrYU1qMVJuYzl0R1BZMGNJRDZzOUU1cy84Ujg1VGVJcg==
