apiVersion: v1
kind: Service
metadata:
  name: node-app-lb
spec:
  type: LoadBalancer
  selector:
    app: node-app
    version: blue  # Initially point to blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
