apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-node-app-blue
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/node-app-blue"  # Adjust this path based on your cluster setup
