apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: node-app-green
spec:
  serviceName: "node-app-green"
  replicas: 3
  selector:
    matchLabels:
      app: node-app
      version: green
  template:
    metadata:
      labels:
        app: node-app
        version: green
    spec:
      containers:
      - name: node-app
        image: public.ecr.aws/a1d6x4r5/devops:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
